version: '3'
services:
  app:
    image: proyecto-api
    restart: always
    ports:
      - 80:80
    networks:
      - postgres-net
      - redis-net
    depends_on:
      - postgres
    external_links:
      - redis:redis

  postgres:
    image: postgres:9.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proyecto
    networks:
      - postgres-net
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  postgres-net:
  redis-net:
    external: true