version: '3'
services:
  app:
    image: proyecto
    restart: always
    ports:
      - 80:80
    networks:
      - postgres-net
      - redis-net
    external_links:
      - redis:redis
      - postgres:posgres

networks:
  postgres-net:
    external: true
  redis-net:
    external: true